apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-atbx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-atbx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0018-app
  name: devfile-sample-atbx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-atbx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-atbx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-atbx@sha256:7a0df3458df6469d6eb01aab35b220a3bb8f7622d27363c7a3f5bc4535a2be1a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
